Add SavingAsXlsx
Kenstin/Portierniaktosiedzi pull request #11
Opened 2017-05-09 19:41 UTC by RePreus

<3

2017-05-09 19:55 UTC, Kenstin requested changes

2017-05-09 19:55 UTC, Kenstin commented on Portierniaktosiedzi/Models/SavingAsXlsx.cs
> +using Portierniaktosiedzi.Models;
unnecessary usings

2017-05-09 19:55 UTC, Kenstin commented on Portierniaktosiedzi/Models/SavingAsXlsx.cs
> +namespace Portierniaktosiedzi.Extensions
wrong namespace

2017-05-09 19:55 UTC, Kenstin commented on Portierniaktosiedzi/Models/SavingAsXlsx.cs
> +            workbook.SaveAs(
workbook.SaveAs(Filename: "kupa", );

2017-05-09 19:55 UTC, Kenstin commented on Portierniaktosiedzi/Models/SavingAsXlsx.cs
> +        public SavingAsXlsx(string path, /*NegativeArray<Day> list,*/ string name)
SaveAsXlsx

2017-05-09 19:55 UTC, Kenstin commented on Portierniaktosiedzi/Models/SavingAsXlsx.cs
> +            for (int i = 0; i < 11; i++)
`tab.Length`

2017-05-09 19:56 UTC, Kenstin commented on Portierniaktosiedzi/Models/SavingAsXlsx.cs
> +        public SavingAsXlsx(string path, /*NegativeArray<Day> list,*/ string name)
XlsxGenerator?

2017-05-09 19:57 UTC, jodua commented on Portierniaktosiedzi/Models/SavingAsXlsx.cs
> +using Portierniaktosiedzi.Models;
kenstin jest unnecessary

2017-05-09 20:24 UTC, RePreus commented on Portierniaktosiedzi/Models/SavingAsXlsx.cs
> +using Portierniaktosiedzi.Models;
you are unnecessary lol

2017-05-10 16:58 UTC, Kenstin approved these changes

2017-05-10 17:00 UTC, merged